export const mockQuestions = [
  {
    id: 1,
    text: 'What is the capital of France?',
    subject: 'Geography',
    difficulty: 'easy',
    options: [
      { id: 'a', text: 'London' },
      { id: 'b', text: 'Paris' },
      { id: 'c', text: 'Berlin' },
      { id: 'd', text: 'Madrid' },
    ],
    correctAnswer: 'b',
    explanation: 'Paris is the capital and largest city of France.',
  },
  {
    id: 2,
    text: 'Which planet is known as the Red Planet?',
    subject: 'Science',
    difficulty: 'easy',
    options: [
      { id: 'a', text: 'Venus' },
      { id: 'b', text: 'Mars' },
      { id: 'c', text: 'Jupiter' },
      { id: 'd', text: 'Saturn' },
    ],
    correctAnswer: 'b',
    explanation: 'Mars is known as the Red Planet due to its reddish appearance caused by iron oxide on its surface.',
  },
  {
    id: 3,
    text: 'What is the largest ocean on Earth?',
    subject: 'Geography',
    difficulty: 'easy',
    options: [
      { id: 'a', text: 'Atlantic Ocean' },
      { id: 'b', text: 'Indian Ocean' },
      { id: 'c', text: 'Pacific Ocean' },
      { id: 'd', text: 'Arctic Ocean' },
    ],
    correctAnswer: 'c',
    explanation: 'The Pacific Ocean is the largest and deepest ocean on Earth.',
  },
  {
    id: 4,
    text: 'What is the chemical symbol for Gold?',
    subject: 'Science',
    difficulty: 'medium',
    options: [
      { id: 'a', text: 'Go' },
      { id: 'b', text: 'Gd' },
      { id: 'c', text: 'Au' },
      { id: 'd', text: 'Ag' },
    ],
    correctAnswer: 'c',
    explanation: 'Au is the chemical symbol for Gold, derived from its Latin name "aurum".',
  },
  {
    id: 5,
    text: 'Who wrote "Romeo and Juliet"?',
    subject: 'Literature',
    difficulty: 'easy',
    options: [
      { id: 'a', text: 'Jane Austen' },
      { id: 'b', text: 'William Shakespeare' },
      { id: 'c', text: 'Charles Dickens' },
      { id: 'd', text: 'Mark Twain' },
    ],
    correctAnswer: 'b',
    explanation: 'William Shakespeare wrote "Romeo and Juliet", one of his most famous tragedies.',
  },
  {
    id: 6,
    text: 'What is the speed of light?',
    subject: 'Science',
    difficulty: 'medium',
    options: [
      { id: 'a', text: '300,000 km/s' },
      { id: 'b', text: '150,000 km/s' },
      { id: 'c', text: '450,000 km/s' },
      { id: 'd', text: '100,000 km/s' },
    ],
    correctAnswer: 'a',
    explanation: 'The speed of light in vacuum is approximately 299,792,458 meters per second or 300,000 km/s.',
  },
  {
    id: 7,
    text: 'What is the smallest prime number?',
    subject: 'Mathematics',
    difficulty: 'easy',
    options: [
      { id: 'a', text: '0' },
      { id: 'b', text: '1' },
      { id: 'c', text: '2' },
      { id: 'd', text: '3' },
    ],
    correctAnswer: 'c',
    explanation: '2 is the smallest and only even prime number.',
  },
  {
    id: 8,
    text: 'What is the capital of Japan?',
    subject: 'Geography',
    difficulty: 'easy',
    options: [
      { id: 'a', text: 'Osaka' },
      { id: 'b', text: 'Kyoto' },
      { id: 'c', text: 'Tokyo' },
      { id: 'd', text: 'Yokohama' },
    ],
    correctAnswer: 'c',
    explanation: 'Tokyo is the capital and the largest metropolitan area of Japan.',
  },
]

export const mockExams = [
  {
    id: 1,
    title: 'General Knowledge Quiz',
    description: 'A comprehensive quiz covering geography, science, and literature.',
    duration: 30,
    totalQuestions: 20,
    passingScore: 60,
    subject: 'General Knowledge',
    questions: [1, 2, 3, 5],
    createdAt: '2024-01-15',
    status: 'active',
  },
  {
    id: 2,
    title: 'Science Fundamentals',
    description: 'Test your knowledge of basic science concepts.',
    duration: 45,
    totalQuestions: 30,
    passingScore: 70,
    subject: 'Science',
    questions: [2, 4, 6],
    createdAt: '2024-01-20',
    status: 'active',
  },
  {
    id: 3,
    title: 'Geography Masters',
    description: 'Challenge yourself with advanced geography questions.',
    duration: 60,
    totalQuestions: 40,
    passingScore: 75,
    subject: 'Geography',
    questions: [1, 3, 8],
    createdAt: '2024-01-25',
    status: 'active',
  },
]

export const mockResults = [
  {
    id: 1,
    examId: 1,
    examTitle: 'General Knowledge Quiz',
    userId: 'user1',
    userName: 'John Doe',
    score: 15,
    totalMarks: 20,
    percentage: 75,
    status: 'passed',
    attemptedAt: '2024-02-10T10:30:00',
    completedAt: '2024-02-10T10:35:00',
    duration: 5,
    answers: [
      { questionId: 1, selected: 'b', isCorrect: true },
      { questionId: 2, selected: 'b', isCorrect: true },
      { questionId: 3, selected: 'c', isCorrect: true },
      { questionId: 5, selected: 'a', isCorrect: false },
    ],
  },
  {
    id: 2,
    examId: 2,
    examTitle: 'Science Fundamentals',
    userId: 'user1',
    userName: 'John Doe',
    score: 24,
    totalMarks: 30,
    percentage: 80,
    status: 'passed',
    attemptedAt: '2024-02-12T14:15:00',
    completedAt: '2024-02-12T14:45:00',
    duration: 30,
    answers: [
      { questionId: 2, selected: 'b', isCorrect: true },
      { questionId: 4, selected: 'c', isCorrect: true },
      { questionId: 6, selected: 'a', isCorrect: true },
    ],
  },
  {
    id: 3,
    examId: 1,
    examTitle: 'General Knowledge Quiz',
    userId: 'user2',
    userName: 'Jane Smith',
    score: 12,
    totalMarks: 20,
    percentage: 60,
    status: 'passed',
    attemptedAt: '2024-02-14T11:00:00',
    completedAt: '2024-02-14T11:06:00',
    duration: 6,
    answers: [
      { questionId: 1, selected: 'b', isCorrect: true },
      { questionId: 2, selected: 'a', isCorrect: false },
      { questionId: 3, selected: 'c', isCorrect: true },
      { questionId: 5, selected: 'b', isCorrect: true },
    ],
  },
]
